function CodeDefine() { 
this.def = new Array();
this.def["stopRequested"] = {file: "ert_main_cpp.html",line:16,type:"var"};
this.def["runModel"] = {file: "ert_main_cpp.html",line:17,type:"var"};
this.def["stopSem"] = {file: "ert_main_cpp.html",line:18,type:"var"};
this.def["baserateTaskSem"] = {file: "ert_main_cpp.html",line:19,type:"var"};
this.def["schedulerThread"] = {file: "ert_main_cpp.html",line:20,type:"var"};
this.def["baseRateThread"] = {file: "ert_main_cpp.html",line:21,type:"var"};
this.def["threadJoinStatus"] = {file: "ert_main_cpp.html",line:22,type:"var"};
this.def["terminatingmodel"] = {file: "ert_main_cpp.html",line:23,type:"var"};
this.def["baseRateTask"] = {file: "ert_main_cpp.html",line:24,type:"fcn"};
this.def["exitFcn"] = {file: "ert_main_cpp.html",line:44,type:"fcn"};
this.def["terminateTask"] = {file: "ert_main_cpp.html",line:50,type:"fcn"};
this.def["main"] = {file: "ert_main_cpp.html",line:67,type:"fcn"};
this.def["Zustandsregler_B"] = {file: "Zustandsregler_cpp.html",line:25,type:"var"};
this.def["Zustandsregler_X"] = {file: "Zustandsregler_cpp.html",line:28,type:"var"};
this.def["Zustandsregler_DW"] = {file: "Zustandsregler_cpp.html",line:31,type:"var"};
this.def["Zustandsregler_M_"] = {file: "Zustandsregler_cpp.html",line:34,type:"var"};
this.def["Zustandsregler_M"] = {file: "Zustandsregler_cpp.html",line:35,type:"var"};
this.def["Zustandsregler.cpp:rt_ertODEUpdateContinuousStates"] = {file: "Zustandsregler_cpp.html",line:45,type:"fcn"};
this.def["Zustandsr_EnabledSubsystem_Init"] = {file: "Zustandsregler_cpp.html",line:129,type:"fcn"};
this.def["Zustandsregler_EnabledSubsystem"] = {file: "Zustandsregler_cpp.html",line:143,type:"fcn"};
this.def["Zustandsregler.cpp:matlabCodegenHandle_matlabCod_i"] = {file: "Zustandsregler_cpp.html",line:158,type:"fcn"};
this.def["Zustandsregler.cpp:matlabCodegenHandle_matlabCodeg"] = {file: "Zustandsregler_cpp.html",line:165,type:"fcn"};
this.def["Zustandsregler_step"] = {file: "Zustandsregler_cpp.html",line:173,type:"fcn"};
this.def["Zustandsregler_derivatives"] = {file: "Zustandsregler_cpp.html",line:393,type:"fcn"};
this.def["Zustandsregler_initialize"] = {file: "Zustandsregler_cpp.html",line:404,type:"fcn"};
this.def["Zustandsregler_terminate"] = {file: "Zustandsregler_cpp.html",line:595,type:"fcn"};
this.def["B_EnabledSubsystem_Zustandsre_T"] = {file: "Zustandsregler_h.html",line:158,type:"type"};
this.def["B_Zustandsregler_T"] = {file: "Zustandsregler_h.html",line:168,type:"type"};
this.def["DW_Zustandsregler_T"] = {file: "Zustandsregler_h.html",line:182,type:"type"};
this.def["X_Zustandsregler_T"] = {file: "Zustandsregler_h.html",line:187,type:"type"};
this.def["XDot_Zustandsregler_T"] = {file: "Zustandsregler_h.html",line:192,type:"type"};
this.def["XDis_Zustandsregler_T"] = {file: "Zustandsregler_h.html",line:197,type:"type"};
this.def["ODE3_IntgData"] = {file: "Zustandsregler_h.html",line:206,type:"type"};
this.def["SL_Bus_Zustandsregler_std_msgs_Float32"] = {file: "Zustandsregler_types_h.html",line:30,type:"type"};
this.def["ros_slros_internal_block_Publ_T"] = {file: "Zustandsregler_types_h.html",line:41,type:"type"};
this.def["ros_slros_internal_block_Subs_T"] = {file: "Zustandsregler_types_h.html",line:52,type:"type"};
this.def["P_EnabledSubsystem_Zustandsre_T"] = {file: "Zustandsregler_types_h.html",line:57,type:"type"};
this.def["P_Zustandsregler_T"] = {file: "Zustandsregler_types_h.html",line:60,type:"type"};
this.def["RT_MODEL_Zustandsregler_T"] = {file: "Zustandsregler_types_h.html",line:63,type:"type"};
this.def["Zustandsregler_P"] = {file: "Zustandsregler_data_cpp.html",line:25,type:"var"};
this.def["long_T"] = {file: "multiword_types_h.html",line:28,type:"type"};
this.def["int128m_T"] = {file: "multiword_types_h.html",line:35,type:"type"};
this.def["cint128m_T"] = {file: "multiword_types_h.html",line:40,type:"type"};
this.def["uint128m_T"] = {file: "multiword_types_h.html",line:44,type:"type"};
this.def["cuint128m_T"] = {file: "multiword_types_h.html",line:49,type:"type"};
this.def["int192m_T"] = {file: "multiword_types_h.html",line:53,type:"type"};
this.def["cint192m_T"] = {file: "multiword_types_h.html",line:58,type:"type"};
this.def["uint192m_T"] = {file: "multiword_types_h.html",line:62,type:"type"};
this.def["cuint192m_T"] = {file: "multiword_types_h.html",line:67,type:"type"};
this.def["int256m_T"] = {file: "multiword_types_h.html",line:71,type:"type"};
this.def["cint256m_T"] = {file: "multiword_types_h.html",line:76,type:"type"};
this.def["uint256m_T"] = {file: "multiword_types_h.html",line:80,type:"type"};
this.def["cuint256m_T"] = {file: "multiword_types_h.html",line:85,type:"type"};
this.def["pointer_T"] = {file: "rtwtypes_h.html",line:28,type:"type"};
this.def["int64_T"] = {file: "rtwtypes_h.html",line:46,type:"type"};
this.def["uint64_T"] = {file: "rtwtypes_h.html",line:53,type:"type"};
this.def["cint64_T"] = {file: "rtwtypes_h.html",line:66,type:"type"};
this.def["cuint64_T"] = {file: "rtwtypes_h.html",line:76,type:"type"};
this.def["MW_AsyncTaskCodeGenInfo_Type"] = {file: "linuxinitialize_cpp.html",line:28,type:"type"};
this.def["linuxinitialize.cpp:MW_TSKMGR_EVENT_DRIVEN_TASKS"] = {file: "linuxinitialize_cpp.html",line:32,type:"var"};
this.def["mw_setAsyncTaskCodeGenInfo"] = {file: "linuxinitialize_cpp.html",line:34,type:"fcn"};
this.def["baseRateInfo_t"] = {file: "linuxinitialize_cpp.html",line:52,type:"type"};
this.def["baseTimerThread"] = {file: "linuxinitialize_cpp.html",line:54,type:"var"};
this.def["attr"] = {file: "linuxinitialize_cpp.html",line:56,type:"var"};
this.def["info"] = {file: "linuxinitialize_cpp.html",line:57,type:"var"};
this.def["sp"] = {file: "linuxinitialize_cpp.html",line:58,type:"var"};
this.def["MW_NUMBER_TIMER_DRIVEN_TASKS"] = {file: "linuxinitialize_cpp.html",line:73,type:"var"};
this.def["MW_NUMBER_TIMER_DRIVEN_TASKS"] = {file: "linuxinitialize_cpp.html",line:74,type:"var"};
this.def["MW_NUMBER_TIMER_DRIVEN_TASKS"] = {file: "linuxinitialize_cpp.html",line:75,type:"var"};
this.def["mw_CreateArmedTimer"] = {file: "linuxinitialize_cpp.html",line:78,type:"fcn"};
this.def["mw_init_timerTaskSem"] = {file: "linuxinitialize_cpp.html",line:105,type:"fcn"};
this.def["mw_CreateUnarmedTimer"] = {file: "linuxinitialize_cpp.html",line:112,type:"fcn"};
this.def["mw_ArmTimer"] = {file: "linuxinitialize_cpp.html",line:139,type:"fcn"};
this.def["mw_WaitForTimerEvent"] = {file: "linuxinitialize_cpp.html",line:164,type:"fcn"};
this.def["mw_WaitForTimerEventCatchup"] = {file: "linuxinitialize_cpp.html",line:180,type:"fcn"};
this.def["baseTimerTask"] = {file: "linuxinitialize_cpp.html",line:221,type:"fcn"};
this.def["schedulerTask"] = {file: "linuxinitialize_cpp.html",line:236,type:"fcn"};
this.def["my_sem_wait"] = {file: "linuxinitialize_cpp.html",line:258,type:"fcn"};
this.def["linuxinitialize.cpp:setThreadPriority"] = {file: "linuxinitialize_cpp.html",line:268,type:"fcn"};
this.def["mw_CreateTask"] = {file: "linuxinitialize_cpp.html",line:283,type:"fcn"};
this.def["myAddBlockForThisEvent"] = {file: "linuxinitialize_cpp.html",line:342,type:"fcn"};
this.def["myAddHandlerForThisEvent"] = {file: "linuxinitialize_cpp.html",line:353,type:"fcn"};
this.def["myRestoreDefaultHandlerForThisEvent"] = {file: "linuxinitialize_cpp.html",line:369,type:"fcn"};
this.def["myRTOSInit"] = {file: "linuxinitialize_cpp.html",line:384,type:"fcn"};
this.def["convertFromBus"] = {file: "slros_busmsg_conversion_cpp.html",line:6,type:"fcn"};
this.def["convertToBus"] = {file: "slros_busmsg_conversion_cpp.html",line:13,type:"fcn"};
this.def["initialize"] = {file: "slros_generic_param_cpp.html",line:9,type:"fcn"};
this.def["initialize_error_codes"] = {file: "slros_generic_param_cpp.html",line:22,type:"fcn"};
this.def["SLROSNodePtr"] = {file: "slros_initialize_cpp.html",line:3,type:"var"};
this.def["SLROSNodeName"] = {file: "slros_initialize_cpp.html",line:4,type:"var"};
this.def["Sub_Zustandsregler_126"] = {file: "slros_initialize_cpp.html",line:7,type:"var"};
this.def["Sub_Zustandsregler_170"] = {file: "slros_initialize_cpp.html",line:10,type:"var"};
this.def["Sub_Zustandsregler_172"] = {file: "slros_initialize_cpp.html",line:13,type:"var"};
this.def["Sub_Zustandsregler_174"] = {file: "slros_initialize_cpp.html",line:16,type:"var"};
this.def["Pub_Zustandsregler_158"] = {file: "slros_initialize_cpp.html",line:19,type:"var"};
this.def["slros_node_init"] = {file: "slros_initialize_cpp.html",line:21,type:"fcn"};
}
CodeDefine.instance = new CodeDefine();
var testHarnessInfo = {OwnerFileName: "", HarnessOwner: "", HarnessName: "", IsTestHarness: "0"};
var relPathToBuildDir = "../ert_main.c";
var fileSep = "\\";
var isPC = true;
function Html2SrcLink() {
	this.html2SrcPath = new Array;
	this.html2Root = new Array;
	this.html2SrcPath["ert_main_cpp.html"] = "../ert_main.cpp";
	this.html2Root["ert_main_cpp.html"] = "ert_main_cpp.html";
	this.html2SrcPath["Zustandsregler_cpp.html"] = "../Zustandsregler.cpp";
	this.html2Root["Zustandsregler_cpp.html"] = "Zustandsregler_cpp.html";
	this.html2SrcPath["Zustandsregler_h.html"] = "../Zustandsregler.h";
	this.html2Root["Zustandsregler_h.html"] = "Zustandsregler_h.html";
	this.html2SrcPath["Zustandsregler_private_h.html"] = "../Zustandsregler_private.h";
	this.html2Root["Zustandsregler_private_h.html"] = "Zustandsregler_private_h.html";
	this.html2SrcPath["Zustandsregler_types_h.html"] = "../Zustandsregler_types.h";
	this.html2Root["Zustandsregler_types_h.html"] = "Zustandsregler_types_h.html";
	this.html2SrcPath["Zustandsregler_data_cpp.html"] = "../Zustandsregler_data.cpp";
	this.html2Root["Zustandsregler_data_cpp.html"] = "Zustandsregler_data_cpp.html";
	this.html2SrcPath["multiword_types_h.html"] = "../multiword_types.h";
	this.html2Root["multiword_types_h.html"] = "multiword_types_h.html";
	this.html2SrcPath["rtwtypes_h.html"] = "../rtwtypes.h";
	this.html2Root["rtwtypes_h.html"] = "rtwtypes_h.html";
	this.html2SrcPath["rtmodel_h.html"] = "../rtmodel.h";
	this.html2Root["rtmodel_h.html"] = "rtmodel_h.html";
	this.html2SrcPath["MW_custom_RTOS_header_h.html"] = "../MW_custom_RTOS_header.h";
	this.html2Root["MW_custom_RTOS_header_h.html"] = "MW_custom_RTOS_header_h.html";
	this.html2SrcPath["MW_target_hardware_resources_h.html"] = "../MW_target_hardware_resources.h";
	this.html2Root["MW_target_hardware_resources_h.html"] = "MW_target_hardware_resources_h.html";
	this.html2SrcPath["linuxinitialize_cpp.html"] = "../../../../../../../../Program Files/MATLAB/R2019b/toolbox/target/codertarget/rtos/src/linuxinitialize.cpp";
	this.html2Root["linuxinitialize_cpp.html"] = "linuxinitialize_cpp.html";
	this.html2SrcPath["slros_busmsg_conversion_cpp.html"] = "../slros_busmsg_conversion.cpp";
	this.html2Root["slros_busmsg_conversion_cpp.html"] = "slros_busmsg_conversion_cpp.html";
	this.html2SrcPath["slros_busmsg_conversion_h.html"] = "../slros_busmsg_conversion.h";
	this.html2Root["slros_busmsg_conversion_h.html"] = "slros_busmsg_conversion_h.html";
	this.html2SrcPath["slros_generic_param_cpp.html"] = "../../../../../../../../Program Files/MATLAB/R2019b/toolbox/ros/slros/src/slros_generic_param.cpp";
	this.html2Root["slros_generic_param_cpp.html"] = "slros_generic_param_cpp.html";
	this.html2SrcPath["slros_initialize_cpp.html"] = "../slros_initialize.cpp";
	this.html2Root["slros_initialize_cpp.html"] = "slros_initialize_cpp.html";
	this.html2SrcPath["slros_initialize_h.html"] = "../slros_initialize.h";
	this.html2Root["slros_initialize_h.html"] = "slros_initialize_h.html";
	this.getLink2Src = function (htmlFileName) {
		 if (this.html2SrcPath[htmlFileName])
			 return this.html2SrcPath[htmlFileName];
		 else
			 return null;
	}
	this.getLinkFromRoot = function (htmlFileName) {
		 if (this.html2Root[htmlFileName])
			 return this.html2Root[htmlFileName];
		 else
			 return null;
	}
}
Html2SrcLink.instance = new Html2SrcLink();
var fileList = [
"ert_main_cpp.html","Zustandsregler_cpp.html","Zustandsregler_h.html","Zustandsregler_private_h.html","Zustandsregler_types_h.html","Zustandsregler_data_cpp.html","multiword_types_h.html","rtwtypes_h.html","rtmodel_h.html","MW_custom_RTOS_header_h.html","MW_target_hardware_resources_h.html","linuxinitialize_cpp.html","slros_busmsg_conversion_cpp.html","slros_busmsg_conversion_h.html","slros_generic_param_cpp.html","slros_initialize_cpp.html","slros_initialize_h.html"];
